2021-10-09	19:56:25		Entered in to train method in Training class.Training started
2021-10-09	19:56:50		Unsuccessful End of Training
2021-10-09	19:57:44		Entered in to train method in Training class.Training started
2021-10-09	19:57:53		Unsuccessful End of Training
2021-10-09	19:57:53		exception occured.exception is OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

2021-10-09	20:02:21		Entered in to train method in Training class.Training started
2021-10-09	20:02:29		Unsuccessful End of Training
2021-10-09	20:02:29		exception occured.exception is OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

2021-10-09	20:26:08		Entered in to train method in Training class.Training started
2021-10-09	20:26:22		Unsuccessful End of Training
2021-10-09	20:26:22		exception occured.exception is OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

2021-10-09	20:28:51		Entered in to train method in Training class.Training started
2021-10-09	20:28:59		Unsuccessful End of Training
2021-10-09	20:28:59		exception occured.exception is OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

2021-10-09	20:29:39		Entered in to train method in Training class.Training started
2021-10-09	20:29:51		Unsuccessful End of Training
2021-10-09	20:29:51		exception occured.exception is OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

2021-10-09	20:30:45		Entered in to train method in Training class.Training started
2021-10-09	20:30:53		Unsuccessful End of Training
2021-10-09	20:30:53		exception occured.exception is OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

2021-10-09	20:32:36		Entered in to train method in Training class.Training started
2021-10-09	20:32:44		Unsuccessful End of Training
2021-10-09	20:32:44		exception occured.exception is OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

2021-10-09	20:40:15		Entered in to train method in Training class.Training started
2021-10-09	20:40:25		Unsuccessful End of Training
2021-10-09	20:40:25		exception occured.exception is OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

2021-10-09	20:41:10		Entered in to train method in Training class.Training started
2021-10-09	20:41:18		Unsuccessful End of Training
2021-10-09	20:41:18		exception occured.exception is OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

2021-10-09	20:42:33		Entered in to train method in Training class.Training started
2021-10-09	20:42:57		Entered in to train method in Training class.train,test,val split successfull
2021-10-09	20:43:10		Entered in to train method in Training class. Model successfully initialized
2021-10-09	20:43:11		Entered in to train method in Training class.Model compile successfull
2021-10-09	20:43:11		Entered in to train method in Training class.Training start time 2021-10-09 20:43:11.042420
2021-10-09	20:43:20		Unsuccessful End of Training
2021-10-09	20:43:20		exception occured.exception is Data cardinality is ambiguous:
  x sizes: 2125
  y sizes: 3635
Make sure all arrays contain the same number of samples.
2021-10-09	20:46:39		Entered in to train method in Training class.Training started
2021-10-09	20:47:00		Entered in to train method in Training class.train,test,val split successfull
2021-10-09	20:47:08		Entered in to train method in Training class. Model successfully initialized
2021-10-09	20:47:08		Entered in to train method in Training class.Model compile successfull
2021-10-09	20:47:08		Entered in to train method in Training class.Training start time 2021-10-09 20:47:08.415147
2021-10-09	20:47:15		Unsuccessful End of Training
2021-10-09	20:47:15		exception occured.exception is Data cardinality is ambiguous:
  x sizes: 2125
  y sizes: 3635
Make sure all arrays contain the same number of samples.
2021-10-09	21:02:46		Entered in to train method in Training class.Training started
2021-10-09	21:03:26		Entered in to train method in Training class.train,test,val split successfull
2021-10-09	21:03:46		Entered in to train method in Training class. Model successfully initialized
2021-10-09	21:03:46		Entered in to train method in Training class.Model compile successfull
2021-10-09	21:03:46		Entered in to train method in Training class.Training start time 2021-10-09 21:03:46.689890
2021-10-09	21:04:04		Unsuccessful End of Training
2021-10-09	21:04:04		exception occured.exception is  Received a label value of 4 which is outside the valid range of [0, 3).  Label values: 2 2 0 0 4 0 3 0 3 3 2 3 4 4 1 0 0 0 3 0 4 3 2 2 3 3 2 2 4 2 0 3
	 [[node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits (defined at \Desktop\Projects\Deep Learning Projects\Mechanical tools classfication\training.py:140) ]] [Op:__inference_train_function_1333]

Function call stack:
train_function

2021-10-10	10:49:57		Entered in to train method in Training class.Training started
2021-10-10	10:50:15		Entered in to train method in Training class.train,test,val split successfull
2021-10-10	10:50:29		Entered in to train method in Training class. Model successfully initialized
2021-10-10	10:50:29		Entered in to train method in Training class.Model compile successfull
2021-10-10	10:50:29		check point directory created
2021-10-10	10:50:29		Entered in to train method in Training class.Training start time 2021-10-10 10:50:29.715501
2021-10-10	10:51:34		Unsuccessful End of Training
2021-10-10	10:51:34		exception occured.exception is 'Failed to format this callback filepath: "vgg19_model/checkpoint-{epoch:02d}-{val_accuracy:.2f}.hdf5". Reason: \'val_accuracy\''
2021-10-10	10:58:41		Entered in to train method in Training class.Training started
2021-10-10	10:58:57		Entered in to train method in Training class.train,test,val split successfull
2021-10-10	10:59:06		Entered in to train method in Training class. Model successfully initialized
2021-10-10	10:59:06		Entered in to train method in Training class.Model compile successfull
2021-10-10	10:59:06		check point directory created
2021-10-10	10:59:06		Entered in to train method in Training class.Training start time 2021-10-10 10:59:06.073619
2021-10-10	13:38:45		Entered in to train method in Training class.Total time taken is 2:39:39.287912
2021-10-10	13:38:45		Entered in to train method in Training class.model saved successfully
2021-10-10	13:38:46		Entered in to train method in Training class.model evaluation started
2021-10-10	13:43:28		Entered in to train method in Training class.classification report               precision    recall  f1-score   support

           0       0.75      0.74      0.74       309
           1       0.47      0.89      0.62        18
           2       0.67      0.69      0.68       284
           3       0.30      0.36      0.33       145
           4       0.29      0.11      0.16        83

    accuracy                           0.60       839
   macro avg       0.49      0.56      0.50       839
weighted avg       0.59      0.60      0.59       839

2021-10-10	13:43:28		Entered in to train method in Training class.confusion matrix is[[229   2  48  23   7]
 [  0  16   1   1   0]
 [ 53   9 196  24   2]
 [ 25   6  49  52  13]
 [  0   1   0  73   9]]
